# Generated by Django 3.0.7 on 2024-07-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_add_salarys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_salarys',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
