# Generated by Django 4.1.3 on 2024-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_auto_20240710_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_salarys',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
